format = """
$directory$git_branch$git_status$cmd_duration
$nix_shell$character
"""

[username]
format = "$user"
show_always = true

[hostname]
format = "@$hostname"
ssh_only = false

[character]
success_symbol = "[»](bold green)"
error_symbol = "[»](bold red)"

[nix_shell]
disabled = false
format = "nix "
style = "bold blue"
